"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ExternalLink } from "@/components/shared/external-link"

export default function PrivacyPolicyPage() {
    return (
        <>
            <Card className="mb-4 sm:mb-10 bg-muted/50 border-muted">
                <CardContent>
                    <p className="text-sm font-medium text-foreground m-0">
                        <strong>Summary:</strong> E-Voting Desktop is committed to the highest standards of data privacy and election integrity. Your Google OAuth data is used strictly to verify your identity locally and communicate with our secure voting backend.
                    </p>
                </CardContent>
            </Card>

            <section id="introduction">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">1. Introduction</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            Welcome to E-Voting Desktop (&#34;we,&#34; &#34;our,&#34; or &#34;us&#34;). We provide a secure desktop voting platform implemented using Tauri and Next.js technologies. This Privacy Policy outlines how your personal data, specifically information provided via Google OAuth 2.0, is collected, stored, and utilized when using our native client.
                        </p>
                    </CardContent>
                </Card>
            </section>

            <section id="data-collection">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">2. Data Collection (OAuth)</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            To facilitate fair and verified elections from your desktop, we request limited information via third-party login providers:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 mt-4">
                            <li>
                                <strong>Google OAuth Data:</strong> When you sign into our Application using Google, we request access to your <strong>email address</strong> and <strong>basic profile data</strong> (name and profile picture). 
                            </li>
                            <li>
                                <strong>Why we need this:</strong> This OAuth profile data is strictly used to authenticate you against our external secure voting database. The desktop application receives a secure token to verify you are a registered organization member or eligible voter. 
                            </li>
                            <li>
                                <strong>What we DO NOT do:</strong> We do not access your Google contacts, drive, emails, or password. We do not sell this data to any third party.
                            </li>
                            <li>
                                <strong>System Information:</strong> Basic diagnostic data (e.g., OS version) may be generated by the app purely to solve crash reports locally.
                            </li>
                        </ul>
                    </CardContent>
                </Card>
            </section>

            <section id="vote-anonymity">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">3. Vote Anonymity & Security</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            <strong>Your Vote is Secret:</strong> Our platform employs cryptographic measures to separate your Google-authenticated identity from your cast ballot. Once a vote is submitted via the desktop application to our servers, it is stored anonymously and cannot be traced back to your email address or Google profile.
                        </p>
                        <p className="mt-4">
                            <strong>Platform Security:</strong> The E-Voting application communicates with our remote backend over encrypted HTTPS/TLS connections ensuring your voting choices and session tokens are never intercepted in transit.
                        </p>
                    </CardContent>
                </Card>
            </section>

            <section id="data-usage">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">4. How We Use Data</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            We use the data obtained through OAuth strictly for core application functionality:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 mt-4">
                            <li>To verify your identity as an authorized voter across desktop and web clients.</li>
                            <li>To prevent double-voting fraud (ensuring one authorized email = one vote).</li>
                            <li>To display your name and profile picture inside the application UI as a logged-in user.</li>
                            <li>To allow administrators to grant specific email addresses access to specific private elections.</li>
                        </ul>
                    </CardContent>
                </Card>
            </section>

            <section id="data-retention">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">5. Data Retention</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            Your OAuth tokens are securely stored locally on your machine using standard secure storage (such as Keychain on macOS or Credential Manager on Windows) and are cleared immediately upon logging out. 
                            Account details tied to your email in our central database can be requested for deletion at any time by contacting our support team or using the in-app account deletion tool.
                        </p>
                    </CardContent>
                </Card>
            </section>

            <section id="contact">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">6. Contact Us</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            For inquiries regarding data privacy or to exercise your data rights, please contact our Data Protection Officer at:
                        </p>
                        <p className="mt-2">
                            <ExternalLink href="mailto:privacy@evoting.sundaresan.dev" className="text-primary font-medium hover:underline cursor-pointer">
                                privacy@evoting.sundaresan.dev
                            </ExternalLink>
                        </p>
                    </CardContent>
                </Card>
            </section>
        </>
    )
}
