export const AUTH_TOKEN_TTL_MS = 60 * 60 * 1000
export const AUTH_TOKEN_RESEND_COOLDOWN_MS = 60 * 1000
export const AUTH_TOKEN_RESEND_COOLDOWN_SECONDS =
  AUTH_TOKEN_RESEND_COOLDOWN_MS / 1000
export const MAX_AUTH_TOKEN_ATTEMPTS = 5
